name: develop - Test, Build and Deploy

on:
  push:
    branches: [ "develop" ]

env:
  REGISTRY: ghcr.io

jobs:
  tests:
    name: Run .NET backend tests
    runs-on: self-hosted
    
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Run tests
        run: dotnet test
        
  build-push-webapi:
    name: Build WebApi image and push to Docker registry
    runs-on: self-hosted
    needs: tests
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/frikyfriky11/argon-webapi
          tags: |
            type=raw,value=latest-develop
            type=sha

      - name: Build Docker image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Argon.WebApi/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-push-webgui:
    name: Build WebGui image and push to Docker registry
    runs-on: self-hosted
    needs: tests
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/frikyfriky11/argon-webgui
          tags: |
            type=raw,value=latest-develop
            type=sha

      - name: Build Docker image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Argon.WebGui/Dockerfile
          push: true
          build-args: |
            BACKEND_API_URI=https://${{ secrets.PUBLIC_HOST_TEST }}/api
            RUNNING_ENVIRONMENT=test
            BUILD_ID=${{ github.run_id }}
            COMMIT_HASH=${{ github.sha }}
            AUTHORITY=${{ secrets.AUTH_AUTHORITY_TEST }}
            CLIENT_ID=${{ secrets.AUTH_CLIENT_ID_TEST }}
            REDIRECT_URI=https://${{ secrets.PUBLIC_HOST_TEST }}/auth/post-sign-in
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy the app to the TEST env
    runs-on: self-hosted
    needs: [ build-push-webapi, build-push-webgui ]
    
    env:
      PUBLIC_HOST_TEST: ${{ secrets.PUBLIC_HOST_TEST }}
      AUTH_AUTHORITY_TEST: ${{ secrets.AUTH_AUTHORITY_TEST }}
      AUTH_CLIENT_ID_TEST: ${{ secrets.AUTH_CLIENT_ID_TEST }}
      COMPOSE_VOLUMES_TEST: ${{ secrets.COMPOSE_VOLUMES_TEST }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Substitute environment variables from docker-compose.test.yml and rename it
      run: envsubst < compose/docker-compose.test.yml > compose/docker-compose.yml
      
    - name: Copy docker-compose.yml to remote server via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: ${{ secrets.REMOTE_SSH_USERNAME }}
        password: ${{ secrets.REMOTE_SSH_PASSWORD }}
        source: "compose/docker-compose.yml"
        target: "${{ secrets.REMOTE_SSH_FOLDER_TEST }}"
        strip_components: 1 # removes the deploy folder when copying over to destination

    - name: Up the Docker compose project on the remote server via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: ${{ secrets.REMOTE_SSH_USERNAME }}
        password: ${{ secrets.REMOTE_SSH_PASSWORD }}
        script: cd ${{ secrets.REMOTE_SSH_FOLDER_TEST }} && docker compose up -d --pull always